# Generated by Django 3.0.5 on 2020-04-07 21:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_resources', '0002_auto_20200402_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyresource',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=0, srid=4326),
            preserve_default=False,
        ),
    ]
