# Generated by Django 3.0.5 on 2020-04-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_resources', '0003_auto_20200415_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyresource',
            name='net_energy',
        ),
    ]
